### ISSUE TITLE
Alerts Sending Multiple Times and for False Positives

### ISSUE THREAD

**Issue by shortjared** [jamesrwhite/minicron#127] opened 2015-06-25 19:26 UTC
The alerting system seems to have some serious issues.

This is all found while running against remote machines with the Minicron agent talking to the hub. I even tried from a completely fresh install of Minicron and fresh database.

If you create a job that is supposed to run at 1 in the morning, but you created the job at 5pm in the day... the alerting system thinks the job has been missed and fires off alerts.

If a job has been missed, it repeatedly sends alerts every minute that the job has been missed. It doesn't just send it once like I would expect.

**Comment by jamesrwhite** [comment] 2015-06-26 09:26
I'll have a look into this, thanks for reporting.

**Comment by jamesrwhite** [comment] 2015-06-27 13:19
> If you create a job that is supposed to run at 1 in the morning, but you created the job at 5pm in the day... the alerting system thinks the job has been missed and fires off alerts.

I believe that issue should be fixed by https://github.com/jamesrwhite/minicron/commit/cf4431d53a736704381b432fc880725db283ed55

> If a job has been missed, it repeatedly sends alerts every minute that the job has been missed. It doesn't just send it once like I would expect.

I may need a bit more help with this though as that definitely isn't the intended behaviour, it should be one alert per missed schedule. The only reason you should get one every minute is if your job schedule was `* * * * *` and for whatever reason they were all missing execution. Could you provide the schedules your seeing this issue with and the data in your `alerts` table?

**Comment by jamesrwhite** [comment] 2015-06-27 13:29
The above commit should resolve:

> If you create a job that is supposed to run at 1 in the morning, but you created the job at 5pm in the day... the alerting system thinks the job has been missed and fires off alerts.

**Closed** 2015-06-27 15:57 UTC
Labels: bug
